name: Auto-publish Newsletter

on:
  # workflow_dispatch:
  #   inputs:
  #     pull-request:
  #       description: 'Pull request number'
  #       required: true
  schedule:
    # At 07:30am PST or 08:30am PDT on Fridays.
    # Will keep checking for 3 hours after.
  
    # Cron runs in UTC
    # PST is UTC-8:00
    # UTC 15:30-8:00 == 7:30am PST
    # https://crontab.guru/#30_16-19_*_*_5
    - cron: "30 15-19 * * 5"

jobs:
  main:
    name: Publish next issue
    runs-on: ubuntu-latest
    steps:
      - name: current datetime
        run: date
   
      # https://github.com/marketplace/actions/auto-merge-pull-request   
      - name: auto-merge
        uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          squash-title: true
          required-labels: auto-publish
          # pull-request: ${{ github.event.inputs.pull-request }}
          # dry-run: true
