name: Test Auto-Merge

on:
  workflow_dispatch:

  schedule:
    # At 07:30am PST or 08:30am PDT on Fridays.
    # Will keep checking for 3 hours after.
  
    # Cron runs in UTC
    # PST is UTC-8:00
    # UTC 15:30-8:00 == 7:30am PST
    # https://crontab.guru/#30_16-19_*_*_5
    - cron: "30 15-19 * * 4,5"

jobs:
  main:
    name: Publish next issue
    runs-on: ubuntu-latest
    steps:      
      - name: current datetime
        run: date
  
      - name: auto-merge
        uses: squalrus/merge-bot@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: true
          labels: auto-publish
          blocking_labels: do not merge
          checks_enabled: true
          method: squash
          delete_source_branch: true
